--CREATE SEQUENCE VENDOR_DETAILS_SEQ
--START WITH 1
--INCREMENT BY 1
--NOCACHE;

DECLARE
    max_id NUMBER;
BEGIN
    SELECT NVL(MAX(vendorid), 0) + 1 INTO max_id FROM VENDOR_DETAILS;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE VENDOR_DETAILS_SEQ START WITH ' || max_id || ' INCREMENT BY 1 NOCACHE';
END;


-- Sequence for State
DECLARE
    max_id NUMBER;
BEGIN
    SELECT NVL(MAX(state_id), 0) + 1 INTO max_id FROM MASTER_STATES;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE STATE_SEQ START WITH ' || max_id || ' INCREMENT BY 1 NOCACHE';
END;
/

-- Sequence for District
DECLARE
    max_id NUMBER;
BEGIN
    SELECT NVL(MAX(district_id), 0) + 1 INTO max_id FROM MASTER_DISTRICTS;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE DISTRICT_SEQ START WITH ' || max_id || ' INCREMENT BY 1 NOCACHE';
END;
/

-- Sequence for IndianNewspaperLanguage
DECLARE
    max_id NUMBER;
BEGIN
    SELECT NVL(MAX(language_id), 0) + 1 INTO max_id FROM MASTER_NEWS_LANGUAGES;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE LANGUAGE_SEQ START WITH ' || max_id || ' INCREMENT BY 1 NOCACHE';
END;
/

-- Sequence for StatewiseLocation
DECLARE
    max_id NUMBER;
BEGIN
    SELECT NVL(MAX(location_id), 0) + 1 INTO max_id FROM MASTER_STATEWISE_LOCATIONS;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE LOCATION_SEQ START WITH ' || max_id || ' INCREMENT BY 1 NOCACHE';
END;
/

-- Sequence for UserDetails
DECLARE
    max_id NUMBER;
BEGIN
    SELECT NVL(MAX(userid), 0) + 1 INTO max_id FROM USER_DETAILS;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE USER_SEQ START WITH ' || max_id || ' INCREMENT BY 1 NOCACHE';
END;
/


